config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :players
  resources :adventures
  resources :npcs
  resources :locations

  root 'site#index'
end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  belongs_to :user
  has_many :encounters
  has_many :notes, as: :notable
  validates :title, :description, presence: true
  accepts_nested_attributes_for :encounters, :allow_destroy => true
  accepts_nested_attributes_for :notes, :allow_destroy => true
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
  belongs_to :adventure
  validates :title, :description, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :notes, as: :notable
  validates :title, :description, presence: true
  accepts_nested_attributes_for :notes, :allow_destroy => true
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :notable, polymorphic: true
  validates :title, :description, presence: true
end

app/models/npc.rb
class Npc < ActiveRecord::Base
  belongs_to :user
  has_many :notes, as: :notable
  validates :name, :description, presence: true
  accepts_nested_attributes_for :notes, :allow_destroy => true
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  has_many :notes, as: :notable
  validates :name, :description, presence: true
  accepts_nested_attributes_for :notes, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :adventures
  has_many :npcs
  has_many :locations
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :authenticate_user!
  before_action :find_adventure, only: [:show, :edit, :update, :destroy]

  def index
    @adventures = Adventure.all
  end

  def show
  end

  def new
    @adventure = Adventure.new
  end

  def create
    @adventure = Adventure.new(adventure_params)
    @adventure.user_id = current_user.id
    if @adventure.save
      redirect_to adventures_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @adventure.update_attributes(adventure_params)
      redirect_to adventure_path(@adventure.id)
    else
      render :edit
    end
  end

  def destroy
    @adventure.destroy
    redirect_to adventures_url
  end

  private

  def adventure_params
    params.require(:adventure).permit(:title, :description, :completed, encounters_attributes: [:title, :description, :reward, :experience, :completed, :id, :_destroy], notes_attributes: [:title, :description, :id, :_destroy])
  end

  def find_adventure
    @adventure = Adventure.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user_id = current_user.id
    if @location.save
      redirect_to locations_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update_attributes(location_params)
      redirect_to location_url(@location.id)
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private

  def find_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:title, :description, notes_attributes: [:title, :description, :id, :_destroy])
  end
end

app/controllers/npc_controller.rb
class NpcController < ApplicationController
  before_action :authenticate_user!
  before_action :find_npc, only: [:show, :edit, :update, :destroy]

  def index
    @npcs = Npc.all
  end

  def show

  end

  def new
    @npc = Npc.new
  end

  def create
    @npc = Npc.new(npc_params)
    @npc.user_id = current_user.id
    if @npc.save
      redirect_to npcs_url
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @npc.update_attributes(npc_params)
      redirect_to npc_path(@npc.id)
    else
      render :edit
    end
  end

  def destroy
    @npc.destroy
    redirect_to npcs_url
  end

  private

  def npc_params
    params.require(:npc).permit(:name, :description)
  end

  def find_npc
    @npc = Npc.find(params[:id])
  end
end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_npc, only: [:show, :edit, :update, :destroy]

  def index
    @npcs = Npc.all
  end

  def show
  end

  def new
    @npc = Npc.new
  end

  def create
    @npc = Npc.new(npc_params)
    @npc.user_id = current_user.id
    if @npc.save
      redirect_to npcs_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @npc.update_attributes(npc_params)
      redirect_to npc_path(@npc.id)
    else
      render :edit
    end
  end

  def destroy
    @npc.destroy
    redirect_to npcs_url
  end

  private

  def npc_params
    params.require(:npc).permit(:name, :description, notes_attributes: [:title, :description, :id, :_destroy])
  end

  def find_npc
    @npc = Npc.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.user_id = current_user.id
    if @player.save
      redirect_to players_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @player.update_attributes(player_params)
      redirect_to player_url(@player.id)
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url
  end

  private

  def find_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :description, notes_attributes: [:title, :description, :id, :_destroy])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!

  def index
    @players = Player.all
    @adventures = Adventure.all
    @locations = Location.all
    @npcs = Npc.all
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/adventures/_form.html.erb
<%= nested_form_for @adventure do |f| %>

  <% if @adventure.errors.any? %>
    <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.check_box :completed %>
    <%= f.label :completed %>
  </div>

  <h2>Encounters</h2>

  <%= f.fields_for :encounters do |encounter_form| %>
    <div>
      <h4>Encounter</h4>
      <div>
        <%= encounter_form.link_to_remove 'Delete Encounter', class: 'red' %>
      </div>
      <div>
        <%= encounter_form.label :title %>
        <%= encounter_form.text_field :title %>
      </div>
      <div>
        <%= encounter_form.label :description %>
        <%= encounter_form.text_area :description %>
      </div>
      <div>
        <%= encounter_form.label :reward %>
        <%= encounter_form.text_field :reward %>
      </div>
      <div>
        <%= encounter_form.label :experience %>
        <%= encounter_form.number_field :experience %>
      </div>
      <div>
        <%= encounter_form.check_box :completed %>
        <%= encounter_form.label :completed %>
      </div>
    </div>
  <% end %>
  <br>
  <div><%= f.link_to_add "Add an Encounter", :encounters, class: 'green' %></div>
  <br>

  <h2>Notes</h2>

  <%= f.fields_for :notes do |notes_form| %>
    <div>
      <h4>Note</h4>
      <%= notes_form.link_to_remove 'Delete Note', class: 'red' %>
      <br>
      <%= notes_form.label :title %>
      <%= notes_form.text_field :title %>
      <br>
      <%= notes_form.label :description %>
      <%= notes_form.text_area :description %>
    </div>
  <% end %>
  <br>
  <div><%= f.link_to_add "Add a note", :notes, class: 'green' %></div>
  <br>
  <div>
    <%= f.submit 'Submit' %>
  </div>

<% end %>

app/views/adventures/edit.html.erb
<h1>Edit <%= @adventure.title %></h1>

<%= render 'form' %>

app/views/adventures/index.html.erb
<h1>Adventures</h1>

<% @adventures.each do |adventure| %>
  <% if adventure.user_id == current_user.id %>
    <div>
      <%= link_to adventure.title, adventure_path(adventure.id) %>
    </div>
  <% end %>
<% end %>

app/views/adventures/new.html.erb
<h1>Create New Adventure</h1>

<%= render 'form' %>

app/views/adventures/show.html.erb
<h1><%= @adventure.title %></h1>

<p><%= @adventure.description %></p>

<p>Completed: <%= @adventure.completed %></p>

<h2>Encounters</h2>

<% @adventure.encounters.each do |encounter| %>
  <h4 class="encounter-header"><%= encounter.title %></h4>
  <ul class="encounter">
    <li><%= encounter.description %></li>
    <li>Reward: <%= encounter.reward %></li>
    <li>Experience: <%= encounter.experience %></li>
    <li>Completed: <%= encounter.completed %></li>
  </ul>
<% end %>

<h2>Notes</h2>
<% @adventure.notes.each do |note| %>
  <h4><%= note.title %></h4>
  <p>
    <%= note.description %>
  </p>
<% end %>

<%= link_to 'Edit Adventure', edit_adventure_path(@adventure.id) %>
<br>
<%= link_to "Delete Adventure", adventure_path(@adventure.id), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DmDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header-wrap">
    <header>
      <h1><%= link_to 'DM Dashboard', root_path %></h1>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'New Player', new_player_path %></li>
            <li><%= link_to 'New NPC', new_npc_path %></li>
            <li><%= link_to 'New Location', new_location_path %></li>
            <li><%= link_to 'New Adventure', new_adventure_path %></li>
            <li class="white">&nbsp;&nbsp;|&nbsp;&nbsp;</li>
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
      <div class="clear"></div>
    </header>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="main-wrap">
    <section class="main-section">
      <%= yield %>
    </section>
  </div>

  <div class="footer-wrap">
    <footer>
      <p>
        Anti-copyright 2014 @ DM Dashboard. All rights are free.
      </p>
    </footer>
  </div>

</body>
</html>

app/views/locations/_form.html.erb
<%= nested_form_for @location do |f| %>

  <% if @location.errors.any? %>
    <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <h2>Notes</h2>

  <%= f.fields_for :notes do |notes_form| %>
    <div>
      <h4>Note</h4>
      <%= notes_form.link_to_remove 'Delete Note', class: 'red' %>
      <br>
      <%= notes_form.label :title %>
      <%= notes_form.text_field :title %>
      <br>
      <%= notes_form.label :description %>
      <%= notes_form.text_area :description %>
    </div>
  <% end %>
  <br>
  <div><%= f.link_to_add "Add a note", :notes, class: 'green' %></div>
  <br>

  <div>
    <%= f.submit 'Submit' %>
  </div>

<% end %>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.title %></h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<% @locations.each do |location| %>
  <% if location.user_id == current_user.id %>
    <div>
      <%= link_to location.title, location_path(location.id) %>
    </div>
  <% end %>
<% end %>

app/views/locations/new.html.erb
<h1>Create New Location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<h1><%= @location.title %></h1>

<p><%= @location.description %></p>

<h2>Notes</h2>
<% @location.notes.each do |note| %>
  <h4><%= note.title %></h4>
  <p>
    <%= note.description %>
  </p>
<% end %>

<%= link_to 'Edit Location', edit_location_path(@location.id) %>
<br>
<%= link_to "Delete Location", location_path(@location.id), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/npcs/_form.html.erb
<%= nested_form_for @npc do |f| %>

  <% if @npc.errors.any? %>
    <ul>
      <% @npc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <h2>Notes</h2>

  <%= f.fields_for :notes do |notes_form| %>
    <div>
      <h4>Note</h4>
      <%= notes_form.link_to_remove 'Delete Note', class: 'red' %>
      <br>
      <%= notes_form.label :title %>
      <%= notes_form.text_field :title %>
      <br>
      <%= notes_form.label :description %>
      <%= notes_form.text_area :description %>
    </div>
  <% end %>
  <br>
  <div><%= f.link_to_add "Add a note", :notes, class: 'green' %></div>
  <br>

  <div>
    <%= f.submit 'Submit' %>
  </div>

<% end %>

app/views/npcs/edit.html.erb
<h1>Edit <%= @npc.name %></h1>

<%= render 'form' %>

app/views/npcs/index.html.erb
<h1>NPCs</h1>

<% @npcs.each do |npc| %>
  <% if npc.user_id == current_user.id %>
    <div>
      <%= link_to npc.name, npc_path(npc.id) %>
    </div>
  <% end %>
<% end %>

app/views/npcs/new.html.erb
<h1>Create New NPC</h1>

<%= render 'form' %>

app/views/npcs/show.html.erb
<h1><%= @npc.name %></h1>

<p><%= @npc.description %></p>

<h2>Notes</h2>
<% @npc.notes.each do |note| %>
  <h4><%= note.title %></h4>
  <p>
    <%= note.description %>
  </p>
<% end %>

<%= link_to 'Edit NPC', edit_npc_path(@npc.id) %>
<br>
<%= link_to "Delete NPC", npc_path(@npc.id), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/players/_form.html.erb
<%= nested_form_for @player do |f| %>

  <% if @player.errors.any? %>
    <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <h2>Notes</h2>

  <%= f.fields_for :notes do |notes_form| %>
    <div>
      <h4>Note</h4>
      <%= notes_form.link_to_remove 'Delete Note', class: 'red' %>
      <br>
      <%= notes_form.label :title %>
      <%= notes_form.text_field :title %>
      <br>
      <%= notes_form.label :description %>
      <%= notes_form.text_area :description %>
    </div>
  <% end %>
  <br>
  <div><%= f.link_to_add "Add a note", :notes, class: 'green' %></div>
  <br>

  <div>
    <%= f.submit 'Submit' %>
  </div>

<% end %>

app/views/players/edit.html.erb
<h1>Edit <%= @player.name %></h1>

<%= render 'form' %>

app/views/players/index.html.erb
<h1>Players</h1>

<% @players.each do |player| %>
  <% if player.user_id == current_user.id %>
    <div>
      <%= link_to player.name, player_path(player.id) %>
    </div>
  <% end %>
<% end %>

app/views/players/new.html.erb
<h1>Create New Player</h1>

<%= render 'form' %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<p><%= @player.description %></p>

<h2>Notes</h2>
<% @player.notes.each do |note| %>
  <h4><%= note.title %></h4>
  <p>
    <%= note.description %>
  </p>
<% end %>

<%= link_to 'Edit Player', edit_player_path(@player.id) %>
<br>
<%= link_to "Delete Player", player_path(@player.id), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/site/index.html.erb
<h1>Dashboard</h1>
<nav class="dash-menu">
  <ul>
    <li class="players">Players</li>
    <li class="adventures">Adventures</li>
    <li class="locations">Locations</li>
    <li class="npcs">NPCs</li>
  </ul>
</nav>
<section class="players-dash dashboard">
  <h2>Players</h2>
  <% @players.each do |player| %>
    <% if player.user_id == current_user.id %>
      <div>
        <%= link_to player.name, player_path(player.id) %>
      </div>
    <% end %>
  <% end %>
</section>
<section class="adventures-dash dashboard">
  <h2>Adventures</h2>
  <% @adventures.each do |adventure| %>
    <% if adventure.user_id == current_user.id %>
      <div>
        <%= link_to adventure.title, adventure_path(adventure.id) %>
      </div>
    <% end %>
  <% end %>
</section>
<section class="locations-dash dashboard">
  <h2>Locations</h2>
  <% @locations.each do |location| %>
    <% if location.user_id == current_user.id %>
      <div>
        <%= link_to location.title, location_path(location.id) %>
      </div>
    <% end %>
  <% end %>
</section>
<section class="npcs-dash dashboard">
  <h2>NPCs</h2>
  <% @npcs.each do |npc| %>
    <% if npc.user_id == current_user.id %>
      <div>
        <%= link_to npc.name, npc_path(npc.id) %>
      </div>
    <% end %>
  <% end %>
</section>
<div class="clear"></div>